# Generated by Django 4.2.6 on 2024-03-01 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rsvp",
            unique_together={("user", "event")},
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="end_datetime_after_start_datetime",
            ),
        ),
    ]
