# Generated by Django 4.2.6 on 2024-03-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_rsvp_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contributioncommitment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='contributioncommitment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contributioncommitment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contributionrequirement',
            name='title',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='status',
        ),
        migrations.AddField(
            model_name='contributioncommitment',
            name='RSVP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.rsvp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributioncommitment',
            name='contribution_requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='events.contributionrequirement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributionrequirement',
            name='contribution_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='events.contributionitem'),
            preserve_default=False,
        ),
    ]
