# Generated by Django 4.2.6 on 2024-03-05 18:28
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def populate_contact(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.update(contact=F("organiser"))


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0005_event_maximum_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="is_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(populate_contact, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="event",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="is_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
