repos:
  -   repo: https://github.com/Riverside-Healthcare/djlint
      rev: v1.34.0
      hooks:
        - id: djlint
  -   repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.3
      hooks:
        - id: ruff
        - id: ruff-format
