contribution_item_data = [
    {"title": "Speaker"},
    {"title": "CDJ"},
    {"title": "Vegan Meal"},
    {"title": "MIDI Cable"},
    {"title": "Microphone"},
    {"title": "Headphones"},
    {"title": "Turntable"},
    {"title": "Sound Mixer"},
    {"title": "Amplifier"},
    {"title": "Lighting Rig"},
    {"title": "Projector"},
    {"title": "Screen"},
    {"title": "Laptop"},
    {"title": "Tablet"},
    {"title": "DJ Controller"},
    {"title": "Drum Machine"},
    {"title": "Synthesizer"},
    {"title": "Stage Monitor"},
    {"title": "Wireless Mic"},
    {"title": "Subwoofer"},
    {"title": "Fog Machine"},
    {"title": "Laser Lights"},
    {"title": "Backup Battery"},
    {"title": "Power Strip"},
    {"title": "Audio Interface"},
    {"title": "Guitar"},
    {"title": "Bass Guitar"},
    {"title": "Keyboard Stand"},
    {"title": "Pop Filter"},
    {"title": "Studio Monitor"},
]
